server:
  port: 8080

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key:
      secret-key:
    end-point:
      uri:
    topic-arn:

